name: Build Beta Font

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install drawbot-skia
          python -m pip install ufo2ft
          python -m pip install defcon
          
      - name: Build font
        run: |
          python scripts/makeBeta.py

      - name: Storing report artifacts
        uses: actions/upload-artifact@master
        with:
          name: beta font
          path: beta
          retention-days: 15
          
      - name: Storing report artifacts
        uses: actions/upload-artifact@master
        with:
          name: proofs
          path: proofing
          retention-days: 15
    
